version: 2
jobs:
  build:
    working_directory: ~/mopub-android-sdk
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout:
          path: ~/mopub-android-sdk

      # Download and cache dependencies (or load them from cache):
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "mopub-sdk/build.gradle" }}-{{ checksum  "mopub-sdk/mopub-sdk-banner/build.gradle" }}-{{ checksum  "mopub-sdk/mopub-sdk-base/build.gradle" }}-{{ checksum  "mopub-sdk/mopub-sdk-interstitial/build.gradle" }}-{{ checksum  "mopub-sdk/mopub-sdk-native-static/build.gradle" }}-{{ checksum  "mopub-sdk/mopub-sdk-native-video/build.gradle" }}-{{ checksum  "mopub-sdk/mopub-sdk-rewardedvideo/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "mopub-sdk/build.gradle" }}-{{ checksum  "mopub-sdk/mopub-sdk-banner/build.gradle" }}-{{ checksum  "mopub-sdk/mopub-sdk-base/build.gradle" }}-{{ checksum  "mopub-sdk/mopub-sdk-interstitial/build.gradle" }}-{{ checksum  "mopub-sdk/mopub-sdk-native-static/build.gradle" }}-{{ checksum  "mopub-sdk/mopub-sdk-native-video/build.gradle" }}-{{ checksum  "mopub-sdk/mopub-sdk-rewardedvideo/build.gradle" }}

      # Build, and then upload AAR artifacts:
      - run:
          name: Build AARs
          command: ./gradlew assembleRelease -PdisablePreDex
      - store_artifacts:
          path: mopub-sdk/mopub-sdk-banner/build/outputs/aar
          destination: aar
      - store_artifacts:
          path: mopub-sdk/mopub-sdk-base/build/outputs/aar
          destination: aar
      - store_artifacts:
          path: mopub-sdk/mopub-sdk-interstitial/build/outputs/aar
          destination: aar
      - store_artifacts:
          path: mopub-sdk/mopub-sdk-native-static/build/outputs/aar
          destination: aar
      - store_artifacts:
          path: mopub-sdk/mopub-sdk-native-video/build/outputs/aar
          destination: aar
      - store_artifacts:
          path: mopub-sdk/mopub-sdk-rewardedvideo/build/outputs/aar
          destination: aar
